In [1]:
import pandas as pd
import numpy as np

In [2]:
pip install cfbd

Requirement already satisfied: cfbd in /Users/kyleberry/opt/anaconda3/lib/python3.8/site-packages (4.4.0)
Requirement already satisfied: python-dateutil>=2.1 in /Users/kyleberry/opt/anaconda3/lib/python3.8/site-packages (from cfbd) (2.8.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/kyleberry/opt/anaconda3/lib/python3.8/site-packages (from cfbd) (2020.6.20)
Requirement already satisfied: six>=1.10 in /Users/kyleberry/opt/anaconda3/lib/python3.8/site-packages (from cfbd) (1.15.0)
Requirement already satisfied: urllib3>=1.23 in /Users/kyleberry/opt/anaconda3/lib/python3.8/site-packages (from cfbd) (1.25.11)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# import package and CFB data from collegefootballdata.com
from __future__ import print_function
import time
import cfbd
from cfbd.rest import ApiException
from pprint import pprint

# configure authorization
configuration = cfbd.Configuration()
configuration.api_key['Authorization'] = '764WJr7XOG8TwqDCfJpNM3PUdPH9Iu5GQNq7pfXCzdDkm8DESnKeaaNMO3DlT9OW'
configuration.api_key_prefix['Authorization'] = 'Bearer'

# get game data for 2010 to 2021 seasons
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
games_2010 = api_instance.get_games(year=2010)
games_2011 = api_instance.get_games(year=2011)
games_2012 = api_instance.get_games(year=2012)
games_2013 = api_instance.get_games(year=2013)
games_2014 = api_instance.get_games(year=2014)
games_2015 = api_instance.get_games(year=2015)
games_2016 = api_instance.get_games(year=2016)
games_2017 = api_instance.get_games(year=2017)
games_2018 = api_instance.get_games(year=2018)
games_2019 = api_instance.get_games(year=2019)
games_2020 = api_instance.get_games(year=2020)
games_2021 = api_instance.get_games(year=2021)

In [4]:
# get team record data for 2010 to 2021 seasons
api_instance = cfbd.GamesApi(cfbd.ApiClient(configuration))
team_records_2010 = api_instance.get_team_records(year=2010)
team_records_2011 = api_instance.get_team_records(year=2011)
team_records_2012 = api_instance.get_team_records(year=2012)
team_records_2013 = api_instance.get_team_records(year=2013)
team_records_2014 = api_instance.get_team_records(year=2014)
team_records_2015 = api_instance.get_team_records(year=2015)
team_records_2016 = api_instance.get_team_records(year=2016)
team_records_2017 = api_instance.get_team_records(year=2017)
team_records_2018 = api_instance.get_team_records(year=2018)
team_records_2019 = api_instance.get_team_records(year=2019)
team_records_2020 = api_instance.get_team_records(year=2020)
team_records_2021 = api_instance.get_team_records(year=2021)

In [7]:
# get recruiting data for 2010 to 2021 seasons
api_instance_recruiting = cfbd.RecruitingApi(cfbd.ApiClient(configuration))
recruiting_2010 = api_instance_recruiting.get_recruiting_teams(year=2010)
recruiting_2011 = api_instance_recruiting.get_recruiting_teams(year=2011)
recruiting_2012 = api_instance_recruiting.get_recruiting_teams(year=2012)
recruiting_2013 = api_instance_recruiting.get_recruiting_teams(year=2013)
recruiting_2014 = api_instance_recruiting.get_recruiting_teams(year=2014)
recruiting_2015 = api_instance_recruiting.get_recruiting_teams(year=2015)
recruiting_2016 = api_instance_recruiting.get_recruiting_teams(year=2016)
recruiting_2017 = api_instance_recruiting.get_recruiting_teams(year=2017)
recruiting_2018 = api_instance_recruiting.get_recruiting_teams(year=2018)
recruiting_2019 = api_instance_recruiting.get_recruiting_teams(year=2019)
recruiting_2020 = api_instance_recruiting.get_recruiting_teams(year=2020)
recruiting_2021 = api_instance_recruiting.get_recruiting_teams(year=2021)
recruiting_2021

[{'points': 327.91, 'rank': 1, 'team': 'Alabama', 'year': 2021},
 {'points': 309.49, 'rank': 2, 'team': 'Ohio State', 'year': 2021},
 {'points': 294.55, 'rank': 3, 'team': 'Georgia', 'year': 2021},
 {'points': 291.37, 'rank': 4, 'team': 'LSU', 'year': 2021},
 {'points': 291.2, 'rank': 5, 'team': 'Clemson', 'year': 2021},
 {'points': 287.38, 'rank': 6, 'team': 'Oregon', 'year': 2021},
 {'points': 285.35, 'rank': 7, 'team': 'Texas A&M', 'year': 2021},
 {'points': 280.72, 'rank': 8, 'team': 'USC', 'year': 2021},
 {'points': 269.15, 'rank': 9, 'team': 'Notre Dame', 'year': 2021},
 {'points': 268.77, 'rank': 10, 'team': 'Michigan', 'year': 2021},
 {'points': 267.92, 'rank': 11, 'team': 'Oklahoma', 'year': 2021},
 {'points': 263.12, 'rank': 12, 'team': 'Miami', 'year': 2021},
 {'points': 261.62, 'rank': 13, 'team': 'Florida', 'year': 2021},
 {'points': 253.91, 'rank': 14, 'team': 'North Carolina', 'year': 2021},
 {'points': 240.8, 'rank': 15, 'team': 'Wisconsin', 'year': 2021},
 {'points': 240.4, 'rank': 16, 'team': 'Tennessee', 'year': 2021},
 {'points': 237.09, 'rank': 17, 'team': 'Texas', 'year': 2021},
 {'points': 234.56, 'rank': 18, 'team': 'Ole Miss', 'year': 2021},
 {'points': 230.29, 'rank': 19, 'team': 'Maryland', 'year': 2021},
 {'points': 216.5, 'rank': 20, 'team': 'Nebraska', 'year': 2021},
 {'points': 216.43, 'rank': 21, 'team': 'Penn State', 'year': 2021},
 {'points': 214.97, 'rank': 22, 'team': 'Florida State', 'year': 2021},
 {'points': 213.89, 'rank': 23, 'team': 'Iowa', 'year': 2021},
 {'points': 213.19, 'rank': 24, 'team': 'Arkansas', 'year': 2021},
 {'points': 210.6, 'rank': 25, 'team': 'Mississippi State', 'year': 2021},
 {'points': 210.45, 'rank': 26, 'team': 'Pittsburgh', 'year': 2021},
 {'points': 210.28, 'rank': 27, 'team': 'Missouri', 'year': 2021},
 {'points': 209.2, 'rank': 28, 'team': 'California', 'year': 2021},
 {'points': 206.5, 'rank': 29, 'team': 'UCLA', 'year': 2021},
 {'points': 205.63, 'rank': 30, 'team': 'Auburn', 'year': 2021},
 {'points': 205.33, 'rank': 31, 'team': 'Virginia', 'year': 2021},
 {'points': 205.02, 'rank': 32, 'team': 'Kentucky', 'year': 2021},
 {'points': 203.23, 'rank': 33, 'team': 'Utah', 'year': 2021},
 {'points': 202.42, 'rank': 34, 'team': 'NC State', 'year': 2021},
 {'points': 201.78, 'rank': 35, 'team': 'Washington', 'year': 2021},
 {'points': 201.66, 'rank': 36, 'team': 'Boston College', 'year': 2021},
 {'points': 199.4, 'rank': 37, 'team': 'Minnesota', 'year': 2021},
 {'points': 198.01, 'rank': 38, 'team': 'Louisville', 'year': 2021},
 {'points': 196.26, 'rank': 39, 'team': 'Oklahoma State', 'year': 2021},
 {'points': 195.07, 'rank': 40, 'team': 'West Virginia', 'year': 2021},
 {'points': 191.67, 'rank': 41, 'team': 'Rutgers', 'year': 2021},
 {'points': 190.66, 'rank': 42, 'team': 'Cincinnati', 'year': 2021},
 {'points': 190.6, 'rank': 43, 'team': 'Michigan State', 'year': 2021},
 {'points': 190.18, 'rank': 44, 'team': 'Baylor', 'year': 2021},
 {'points': 189.84, 'rank': 45, 'team': 'Virginia Tech', 'year': 2021},
 {'points': 187.31, 'rank': 46, 'team': 'Memphis', 'year': 2021},
 {'points': 186.82, 'rank': 47, 'team': 'Georgia Tech', 'year': 2021},
 {'points': 185.98, 'rank': 48, 'team': 'Arizona State', 'year': 2021},
 {'points': 184.46, 'rank': 49, 'team': 'Vanderbilt', 'year': 2021},
 {'points': 184.3, 'rank': 50, 'team': 'Northwestern', 'year': 2021},
 {'points': 183.58, 'rank': 51, 'team': 'Stanford', 'year': 2021},
 {'points': 183.13, 'rank': 52, 'team': 'Kansas', 'year': 2021},
 {'points': 181.61, 'rank': 53, 'team': 'SMU', 'year': 2021},
 {'points': 177.78, 'rank': 54, 'team': 'Indiana', 'year': 2021},
 {'points': 177.69, 'rank': 55, 'team': 'UCF', 'year': 2021},
 {'points': 176.98, 'rank': 56, 'team': 'Kansas State', 'year': 2021},
 {'points': 176.5, 'rank': 57, 'team': 'Syracuse', 'year': 2021},
 {'points': 176.16, 'rank': 58, 'team': 'Duke', 'year': 2021},
 {'points': 175.58, 'rank': 59, 'team': 'Iowa State', 'year': 2021},
 {'points': 172.58, 'rank': 60, 'team': 'Washington State', 'year': 2021},
 {'points': 171.83, 'rank': 61, 'team': 'TCU', 'year': 2021},
 {'points': 169.98, 'rank': 62, 'team': 'San Diego State', 'year': 2021},
 {'points': 167.63, 'rank': 63, 'team': 'South Florida', 'year': 2021},
 {'points': 167.13, 'rank': 64, 'team': 'Texas Tech', 'year': 2021},
 {'points': 167.11, 'rank': 65, 'team': 'Colorado', 'year': 2021},
 {'points': 165.75, 'rank': 66, 'team': 'Wake Forest', 'year': 2021},
 {'points': 163.18, 'rank': 67, 'team': 'Toledo', 'year': 2021},
 {'points': 161.89, 'rank': 68, 'team': 'UNLV', 'year': 2021},
 {'points': 161.14, 'rank': 69, 'team': 'Appalachian State', 'year': 2021},
 {'points': 161.13, 'rank': 70, 'team': 'Boise State', 'year': 2021},
 {'points': 159.77, 'rank': 71, 'team': 'BYU', 'year': 2021},
 {'points': 159.72, 'rank': 72, 'team': 'Purdue', 'year': 2021},
 {'points': 159.12, 'rank': 73, 'team': 'Illinois', 'year': 2021},
 {'points': 159.11, 'rank': 74, 'team': 'Fresno State', 'year': 2021},
 {'points': 157.25, 'rank': 75, 'team': 'Arizona', 'year': 2021},
 {'points': 157.05, 'rank': 76, 'team': 'South Carolina', 'year': 2021},
 {'points': 156.56, 'rank': 77, 'team': 'Tulane', 'year': 2021},
 {'points': 154.8, 'rank': 78, 'team': 'UT San Antonio', 'year': 2021},
 {'points': 154.78, 'rank': 79, 'team': 'Louisiana', 'year': 2021},
 {'points': 153.89, 'rank': 80, 'team': 'North Texas', 'year': 2021},
 {'points': 153.47, 'rank': 81, 'team': 'Houston', 'year': 2021},
 {'points': 153.21, 'rank': 82, 'team': 'Florida Atlantic', 'year': 2021},
 {'points': 152.13, 'rank': 83, 'team': 'Florida International', 'year': 2021},
 {'points': 150.67, 'rank': 84, 'team': 'Coastal Carolina', 'year': 2021},
 {'points': 147.9, 'rank': 85, 'team': 'Jackson State', 'year': 2021},
 {'points': 146.32, 'rank': 86, 'team': 'Nevada', 'year': 2021},
 {'points': 146.12, 'rank': 87, 'team': 'Central Michigan', 'year': 2021},
 {'points': 146.03, 'rank': 88, 'team': 'Miami (OH)', 'year': 2021},
 {'points': 144.67, 'rank': 89, 'team': 'Colorado State', 'year': 2021},
 {'points': 144.16, 'rank': 90, 'team': 'Air Force', 'year': 2021},
 {'points': 142.59, 'rank': 91, 'team': 'Northern Illinois', 'year': 2021},
 {'points': 141.76, 'rank': 92, 'team': 'Georgia Southern', 'year': 2021},
 {'points': 141.39, 'rank': 93, 'team': 'Rice', 'year': 2021},
 {'points': 140.75, 'rank': 94, 'team': 'New Mexico', 'year': 2021},
 {'points': 140.07, 'rank': 95, 'team': 'Ball State', 'year': 2021},
 {'points': 139.28, 'rank': 96, 'team': 'East Carolina', 'year': 2021},
 {'points': 139.11, 'rank': 97, 'team': 'Western Michigan', 'year': 2021},
 {'points': 137.78, 'rank': 98, 'team': 'Buffalo', 'year': 2021},
 {'points': 137.6, 'rank': 99, 'team': 'Ohio', 'year': 2021},
 {'points': 135.74, 'rank': 100, 'team': 'Old Dominion', 'year': 2021},
 {'points': 134.83, 'rank': 101, 'team': 'Charlotte', 'year': 2021},
 {'points': 134.55, 'rank': 102, 'team': 'Georgia State', 'year': 2021},
 {'points': 133.73, 'rank': 103, 'team': 'Bowling Green', 'year': 2021},
 {'points': 133.65, 'rank': 104, 'team': 'Troy', 'year': 2021},
 {'points': 132.83, 'rank': 105, 'team': 'Temple', 'year': 2021},
 {'points': 132.61, 'rank': 106, 'team': 'Arkansas State', 'year': 2021},
 {'points': 131.51, 'rank': 107, 'team': 'Navy', 'year': 2021},
 {'points': 131.45, 'rank': 108, 'team': 'Oregon State', 'year': 2021},
 {'points': 131.27, 'rank': 109, 'team': 'Army', 'year': 2021},
 {'points': 130.41, 'rank': 110, 'team': 'Wyoming', 'year': 2021},
 {'points': 129.14, 'rank': 111, 'team': 'Liberty', 'year': 2021},
 {'points': 128.54, 'rank': 112, 'team': 'Eastern Michigan', 'year': 2021},
 {'points': 127.64, 'rank': 113, 'team': 'Louisiana Monroe', 'year': 2021},
 {'points': 126.9, 'rank': 114, 'team': 'New Mexico State', 'year': 2021},
 {'points': 125.11, 'rank': 115, 'team': 'Connecticut', 'year': 2021},
 {'points': 123.44, 'rank': 116, 'team': 'UAB', 'year': 2021},
 {'points': 121.74, 'rank': 117, 'team': 'UMass', 'year': 2021},
 {'points': 119.36, 'rank': 118, 'team': 'Kent State', 'year': 2021},
 {'points': 113.25, 'rank': 119, 'team': 'Akron', 'year': 2021},
 {'points': 112.81, 'rank': 120, 'team': 'San José State', 'year': 2021},
 {'points': 108.45, 'rank': 121, 'team': 'Louisiana Tech', 'year': 2021},
 {'points': 107.68, 'rank': 122, 'team': 'South Alabama', 'year': 2021},
 {'points': 107.22, 'rank': 123, 'team': 'Middle Tennessee', 'year': 2021},
 {'points': 104.36, 'rank': 124, 'team': 'Southern Mississippi', 'year': 2021},
 {'points': 101.55, 'rank': 125, 'team': 'Marshall', 'year': 2021},
 {'points': 97.89, 'rank': 126, 'team': 'Tulsa', 'year': 2021},
 {'points': 90.15, 'rank': 127, 'team': "Hawai'i", 'year': 2021},
 {'points': 80.92, 'rank': 128, 'team': 'Northern Arizona', 'year': 2021},
 {'points': 70.08, 'rank': 129, 'team': 'Harvard', 'year': 2021},
 {'points': 69.11, 'rank': 130, 'team': 'Princeton', 'year': 2021},
 {'points': 62.42, 'rank': 131, 'team': 'Cal Poly', 'year': 2021},
 {'points': 62.38, 'rank': 132, 'team': 'Idaho', 'year': 2021},
 {'points': 61.37, 'rank': 133, 'team': 'Yale', 'year': 2021},
 {'points': 60.62, 'rank': 134, 'team': 'UTEP', 'year': 2021},
 {'points': 55.32, 'rank': 135, 'team': 'Utah State', 'year': 2021},
 {'points': 49.62, 'rank': 136, 'team': 'Western Kentucky', 'year': 2021},
 {'points': 48.13, 'rank': 138, 'team': 'Eastern Washington', 'year': 2021},
 {'points': 47.87, 'rank': 139, 'team': 'Pennsylvania', 'year': 2021},
 {'points': 46.14, 'rank': 140, 'team': 'James Madison', 'year': 2021},
 {'points': 39.38, 'rank': 141, 'team': 'Lamar', 'year': 2021},
 {'points': 38.9, 'rank': 142, 'team': 'North Carolina A&T', 'year': 2021},
 {'points': 37.22, 'rank': 143, 'team': 'Northern Iowa', 'year': 2021},
 {'points': 36.77, 'rank': 144, 'team': 'Stephen F. Austin', 'year': 2021},
 {'points': 31.22, 'rank': 145, 'team': 'UC Davis', 'year': 2021},
 {'points': 30.3, 'rank': 146, 'team': 'Central Arkansas', 'year': 2021},
 {'points': 29.42, 'rank': 147, 'team': 'Georgetown', 'year': 2021},
 {'points': 28.48, 'rank': 148, 'team': 'Samford', 'year': 2021},
 {'points': 27.3, 'rank': 149, 'team': 'Howard', 'year': 2021},
 {'points': 26.96, 'rank': 150, 'team': 'Morgan State', 'year': 2021},
 {'points': 25.25, 'rank': 151, 'team': 'South Dakota', 'year': 2021},
 {'points': 24.7, 'rank': 152, 'team': 'Montana State', 'year': 2021},
 {'points': 24.64, 'rank': 153, 'team': 'Southern Utah', 'year': 2021},
 {'points': 24.49, 'rank': 154, 'team': 'Grambling', 'year': 2021},
 {'points': 24.23, 'rank': 155, 'team': 'Austin Peay', 'year': 2021},
 {'points': 21.96, 'rank': 156, 'team': 'Tennessee Tech', 'year': 2021},
 {'points': 20.61, 'rank': 157, 'team': 'Kennesaw State', 'year': 2021},
 {'points': 19.5, 'rank': 158, 'team': 'Charleston Southern', 'year': 2021},
 {'points': 18.29, 'rank': 159, 'team': 'Columbia', 'year': 2021},
 {'points': 16.83, 'rank': 160, 'team': 'Jacksonville State', 'year': 2021},
 {'points': 16.08, 'rank': 161, 'team': 'Sacramento State', 'year': 2021},
 {'points': 15.57, 'rank': 162, 'team': 'Brown', 'year': 2021},
 {'points': 15.36, 'rank': 163, 'team': 'Alabama A&M', 'year': 2021},
 {'points': 14.77, 'rank': 164, 'team': 'Lehigh', 'year': 2021},
 {'points': 14.18, 'rank': 165, 'team': 'Prairie View', 'year': 2021},
 {'points': 13.76, 'rank': 166, 'team': 'North Dakota', 'year': 2021},
 {'points': 13.67, 'rank': 167, 'team': 'Sam Houston State', 'year': 2021},
 {'points': 13.3, 'rank': 168, 'team': 'William & Mary', 'year': 2021},
 {'points': 13.17, 'rank': 169, 'team': 'McNeese', 'year': 2021},
 {'points': 13.15, 'rank': 170, 'team': 'Tennessee State', 'year': 2021},
 {'points': 12.65, 'rank': 172, 'team': 'Southern Illinois', 'year': 2021},
 {'points': 12.61, 'rank': 173, 'team': 'Western Carolina', 'year': 2021},
 {'points': 12.51, 'rank': 174, 'team': 'Maine', 'year': 2021},
 {'points': 12.15, 'rank': 175, 'team': 'Chattanooga', 'year': 2021},
 {'points': 12.14, 'rank': 176, 'team': 'Duquesne', 'year': 2021},
 {'points': 11.04, 'rank': 177, 'team': 'Texas Southern', 'year': 2021},
 {'points': 10.54, 'rank': 178, 'team': 'Towson', 'year': 2021},
 {'points': 10.53, 'rank': 179, 'team': 'Villanova', 'year': 2021},
 {'points': 10.53, 'rank': 180, 'team': 'Northwestern State', 'year': 2021},
 {'points': 10.14, 'rank': 181, 'team': 'Holy Cross', 'year': 2021},
 {'points': 10.14, 'rank': 182, 'team': 'Lafayette', 'year': 2021},
 {'points': 9.46, 'rank': 183, 'team': 'Texas State', 'year': 2021},
 {'points': 9.32, 'rank': 184, 'team': 'San Diego', 'year': 2021},
 {'points': 8.92, 'rank': 185, 'team': 'Gardner-Webb', 'year': 2021},
 {'points': 8.92, 'rank': 186, 'team': 'Rhode Island', 'year': 2021},
 {'points': 8.69, 'rank': 187, 'team': 'Fordham', 'year': 2021},
 {'points': 8.31, 'rank': 188, 'team': 'Northern Colorado', 'year': 2021},
 {'points': 7.31, 'rank': 189, 'team': 'Albany', 'year': 2021},
 {'points': 7.3, 'rank': 190, 'team': 'Montana', 'year': 2021},
 {'points': 7.3, 'rank': 191, 'team': 'Portland State', 'year': 2021},
 {'points': 6.8, 'rank': 192, 'team': 'Campbell', 'year': 2021},
 {'points': 5.8, 'rank': 193, 'team': 'Wofford', 'year': 2021}]

In [8]:
# get return playing production data for 2014 to 2021 seasons
api_instance_players = cfbd.PlayersApi(cfbd.ApiClient(configuration))
returning_prod_2014 = api_instance_players.get_returning_production(year=2014)
returning_prod_2015 = api_instance_players.get_returning_production(year=2015)
returning_prod_2016 = api_instance_players.get_returning_production(year=2016)
returning_prod_2017 = api_instance_players.get_returning_production(year=2017)
returning_prod_2018 = api_instance_players.get_returning_production(year=2018)
returning_prod_2019 = api_instance_players.get_returning_production(year=2019)
returning_prod_2020 = api_instance_players.get_returning_production(year=2020)
returning_prod_2021 = api_instance_players.get_returning_production(year=2021)

In [9]:
# get team talent composite ranking data for 2015 to 2021 seasons
api_instance_teams = cfbd.TeamsApi(cfbd.ApiClient(configuration))
team_talent_2015 = api_instance_teams.get_talent(year=2015)
team_talent_2016 = api_instance_teams.get_talent(year=2016)
team_talent_2017 = api_instance_teams.get_talent(year=2017)
team_talent_2018 = api_instance_teams.get_talent(year=2018)
team_talent_2019 = api_instance_teams.get_talent(year=2019)
team_talent_2020 = api_instance_teams.get_talent(year=2020)
team_talent_2021 = api_instance_teams.get_talent(year=2021)

In [10]:
type(team_talent_2016)

list

In [11]:
test3 = [{'school': 'Alabama', 'talent': 981.9, 'year': 2015},
 {'school': 'USC', 'talent': 926.71, 'year': 2015},
 {'school': 'Ohio State', 'talent': 907.32, 'year': 2015},
 {'school': 'Florida State', 'talent': 889.92, 'year': 2015},
 {'school': 'LSU', 'talent': 889.37, 'year': 2015},
 {'school': 'Georgia', 'talent': 877.74, 'year': 2015},
 {'school': 'Auburn', 'talent': 865.41, 'year': 2015},
 {'school': 'Notre Dame', 'talent': 857.33, 'year': 2015},
 {'school': 'Michigan', 'talent': 851.12, 'year': 2015},
 {'school': 'Texas A&M', 'talent': 830.34, 'year': 2015},
 {'school': 'Texas', 'talent': 821.26, 'year': 2015},
 {'school': 'Tennessee', 'talent': 810.53, 'year': 2015},
 {'school': 'Clemson', 'talent': 807.56, 'year': 2015},
 {'school': 'UCLA', 'talent': 793.22, 'year': 2015},
 {'school': 'Florida', 'talent': 789.79, 'year': 2015},
 {'school': 'Oklahoma', 'talent': 775.9, 'year': 2015},
 {'school': 'Miami', 'talent': 773.23, 'year': 2015},
 {'school': 'Stanford', 'talent': 765.98, 'year': 2015},
 {'school': 'Ole Miss', 'talent': 764.34, 'year': 2015},
 {'school': 'Oregon', 'talent': 757.52, 'year': 2015},
 {'school': 'Penn State', 'talent': 732.36, 'year': 2015},
 {'school': 'South Carolina', 'talent': 725.72, 'year': 2015},
 {'school': 'Michigan State', 'talent': 715.3, 'year': 2015},
 {'school': 'Nebraska', 'talent': 699.89, 'year': 2015},
 {'school': 'Arkansas', 'talent': 695.04, 'year': 2015},
 {'school': 'North Carolina', 'talent': 683.03, 'year': 2015},
 {'school': 'Arizona State', 'talent': 680.87, 'year': 2015},
 {'school': 'Mississippi State', 'talent': 680.06, 'year': 2015},
 {'school': 'Washington', 'talent': 667.45, 'year': 2015},
 {'school': 'Virginia', 'talent': 667.05, 'year': 2015},
 {'school': 'Baylor', 'talent': 660.35, 'year': 2015},
 {'school': 'Virginia Tech', 'talent': 658.38, 'year': 2015},
 {'school': 'Oklahoma State', 'talent': 651.83, 'year': 2015},
 {'school': 'Missouri', 'talent': 642.93, 'year': 2015},
 {'school': 'Texas Tech', 'talent': 641.07, 'year': 2015},
 {'school': 'Louisville', 'talent': 641.05, 'year': 2015},
 {'school': 'Wisconsin', 'talent': 635.77, 'year': 2015},
 {'school': 'Kentucky', 'talent': 634.52, 'year': 2015},
 {'school': 'TCU', 'talent': 630.38, 'year': 2015},
 {'school': 'California', 'talent': 626.0, 'year': 2015},
 {'school': 'West Virginia', 'talent': 625.85, 'year': 2015},
 {'school': 'Pittsburgh', 'talent': 611.18, 'year': 2015},
 {'school': 'NC State', 'talent': 610.33, 'year': 2015},
 {'school': 'Vanderbilt', 'talent': 609.76, 'year': 2015},
 {'school': 'Arizona', 'talent': 606.92, 'year': 2015},
 {'school': 'Maryland', 'talent': 603.76, 'year': 2015},
 {'school': 'Rutgers', 'talent': 602.35, 'year': 2015},
 {'school': 'Northwestern', 'talent': 595.75, 'year': 2015},
 {'school': 'Georgia Tech', 'talent': 590.34, 'year': 2015},
 {'school': 'Utah', 'talent': 574.41, 'year': 2015},
 {'school': 'Iowa', 'talent': 573.06, 'year': 2015},
 {'school': 'Boise State', 'talent': 568.96, 'year': 2015},
 {'school': 'Duke', 'talent': 563.19, 'year': 2015},
 {'school': 'Indiana', 'talent': 559.08, 'year': 2015},
 {'school': 'Oregon State', 'talent': 544.66, 'year': 2015},
 {'school': 'Colorado', 'talent': 542.06, 'year': 2015},
 {'school': 'Washington State', 'talent': 540.86, 'year': 2015},
 {'school': 'Boston College', 'talent': 534.6, 'year': 2015},
 {'school': 'Purdue', 'talent': 534.26, 'year': 2015},
 {'school': 'Illinois', 'talent': 530.96, 'year': 2015},
 {'school': 'South Florida', 'talent': 529.65, 'year': 2015},
 {'school': 'Iowa State', 'talent': 529.12, 'year': 2015},
 {'school': 'BYU', 'talent': 521.43, 'year': 2015},
 {'school': 'Minnesota', 'talent': 516.1, 'year': 2015},
 {'school': 'Houston', 'talent': 511.45, 'year': 2015},
 {'school': 'Syracuse', 'talent': 508.8, 'year': 2015},
 {'school': 'Kansas State', 'talent': 503.64, 'year': 2015},
 {'school': 'Kansas', 'talent': 499.97, 'year': 2015},
 {'school': 'Wake Forest', 'talent': 497.48, 'year': 2015},
 {'school': 'San Diego State', 'talent': 494.77, 'year': 2015},
 {'school': 'Cincinnati', 'talent': 494.65, 'year': 2015},
 {'school': 'Marshall', 'talent': 489.77, 'year': 2015},
 {'school': 'UCF', 'talent': 484.54, 'year': 2015},
 {'school': 'Southern Mississippi', 'talent': 470.84, 'year': 2015},
 {'school': 'SMU', 'talent': 446.83, 'year': 2015},
 {'school': 'Western Michigan', 'talent': 442.13, 'year': 2015},
 {'school': 'Louisiana Tech', 'talent': 437.99, 'year': 2015},
 {'school': 'Bowling Green', 'talent': 433.59, 'year': 2015},
 {'school': 'Louisiana', 'talent': 430.17, 'year': 2015},
 {'school': 'Toledo', 'talent': 429.03, 'year': 2015},
 {'school': 'Akron', 'talent': 412.65, 'year': 2015},
 {'school': 'Middle Tennessee', 'talent': 409.82, 'year': 2015},
 {'school': 'Tulane', 'talent': 408.22, 'year': 2015},
 {'school': 'Arkansas State', 'talent': 408.08, 'year': 2015},
 {'school': 'Temple', 'talent': 405.92, 'year': 2015},
 {'school': 'Tulsa', 'talent': 404.03, 'year': 2015},
 {'school': 'East Carolina', 'talent': 403.62, 'year': 2015},
 {'school': 'Fresno State', 'talent': 402.58, 'year': 2015},
 {'school': 'Connecticut', 'talent': 402.23, 'year': 2015},
 {'school': 'Florida Atlantic', 'talent': 401.61, 'year': 2015},
 {'school': 'Rice', 'talent': 399.58, 'year': 2015},
 {'school': 'Miami (OH)', 'talent': 397.13, 'year': 2015},
 {'school': 'Georgia Southern', 'talent': 391.18, 'year': 2015},
 {'school': 'Colorado State', 'talent': 389.1, 'year': 2015},
 {'school': "Hawai'i", 'talent': 385.63, 'year': 2015},
 {'school': 'Memphis', 'talent': 381.8, 'year': 2015},
 {'school': 'North Texas', 'talent': 380.69, 'year': 2015},
 {'school': 'Northern Illinois', 'talent': 380.69, 'year': 2015},
 {'school': 'Nevada', 'talent': 380.53, 'year': 2015},
 {'school': 'San José State', 'talent': 379.6, 'year': 2015},
 {'school': 'Central Michigan', 'talent': 376.81, 'year': 2015},
 {'school': 'South Alabama', 'talent': 367.16, 'year': 2015},
 {'school': 'Texas State', 'talent': 360.49, 'year': 2015},
 {'school': 'Florida International', 'talent': 360.11, 'year': 2015},
 {'school': 'UT San Antonio', 'talent': 356.37, 'year': 2015},
 {'school': 'Western Kentucky', 'talent': 353.5, 'year': 2015},
 {'school': 'Ball State', 'talent': 349.94, 'year': 2015},
 {'school': 'New Mexico', 'talent': 341.72, 'year': 2015},
 {'school': 'Eastern Michigan', 'talent': 341.36, 'year': 2015},
 {'school': 'Kent State', 'talent': 338.4, 'year': 2015},
 {'school': 'Georgia State', 'talent': 335.67, 'year': 2015},
 {'school': 'Troy', 'talent': 335.43, 'year': 2015},
 {'school': 'UNLV', 'talent': 332.69, 'year': 2015},
 {'school': 'Utah State', 'talent': 331.44, 'year': 2015},
 {'school': 'Ohio', 'talent': 330.61, 'year': 2015},
 {'school': 'UMass', 'talent': 323.73, 'year': 2015},
 {'school': 'Old Dominion', 'talent': 319.6, 'year': 2015},
 {'school': 'Buffalo', 'talent': 316.44, 'year': 2015},
 {'school': 'Wyoming', 'talent': 314.72, 'year': 2015},
 {'school': 'Appalachian State', 'talent': 312.88, 'year': 2015},
 {'school': 'Navy', 'talent': 306.87, 'year': 2015},
 {'school': 'Charlotte', 'talent': 304.05, 'year': 2015},
 {'school': 'Louisiana Monroe', 'talent': 292.73, 'year': 2015},
 {'school': 'Idaho', 'talent': 262.39, 'year': 2015},
 {'school': 'UTEP', 'talent': 256.12, 'year': 2015},
 {'school': 'New Mexico State', 'talent': 251.16, 'year': 2015},
 {'school': 'UAB', 'talent': 236.34, 'year': 2015},
 {'school': 'Northern Iowa', 'talent': 202.77, 'year': 2015},
 {'school': 'Army', 'talent': 186.45, 'year': 2015},
 {'school': 'Yale', 'talent': 181.76, 'year': 2015},
 {'school': 'Jacksonville State', 'talent': 173.32, 'year': 2015},
 {'school': 'Chattanooga', 'talent': 137.06, 'year': 2015},
 {'school': 'Portland State', 'talent': 123.61, 'year': 2015},
 {'school': 'Youngstown State', 'talent': 116.79, 'year': 2015},
 {'school': 'Bethune-Cookman', 'talent': 116.09, 'year': 2015},
 {'school': 'South Carolina State', 'talent': 105.01, 'year': 2015},
 {'school': 'Stephen F. Austin', 'talent': 103.72, 'year': 2015},
 {'school': 'Cal Poly', 'talent': 97.73, 'year': 2015},
 {'school': 'Samford', 'talent': 95.68, 'year': 2015},
 {'school': 'Illinois State', 'talent': 92.42, 'year': 2015},
 {'school': 'Murray State', 'talent': 89.72, 'year': 2015},
 {'school': 'James Madison', 'talent': 84.74, 'year': 2015},
 {'school': 'North Dakota State', 'talent': 82.26, 'year': 2015},
 {'school': 'Jackson State', 'talent': 78.26, 'year': 2015},
 {'school': 'Indiana State', 'talent': 74.6, 'year': 2015},
 {'school': 'Tennessee State', 'talent': 74.37, 'year': 2015},
 {'school': 'Towson', 'talent': 74.05, 'year': 2015},
 {'school': 'Pennsylvania', 'talent': 73.07, 'year': 2015},
 {'school': 'Air Force', 'talent': 70.95, 'year': 2015},
 {'school': 'Northern Arizona', 'talent': 68.35, 'year': 2015},
 {'school': 'Abilene Christian', 'talent': 66.43, 'year': 2015},
 {'school': 'Montana', 'talent': 64.46, 'year': 2015},
 {'school': 'Wagner', 'talent': 64.14, 'year': 2015},
 {'school': 'UT Martin', 'talent': 62.12, 'year': 2015},
 {'school': 'Stony Brook', 'talent': 61.96, 'year': 2015},
 {'school': 'Furman', 'talent': 61.89, 'year': 2015},
 {'school': 'Southern Illinois', 'talent': 60.76, 'year': 2015},
 {'school': 'Hampton', 'talent': 58.39, 'year': 2015},
 {'school': 'Southeastern Louisiana', 'talent': 58.08, 'year': 2015},
 {'school': 'Villanova', 'talent': 57.42, 'year': 2015},
 {'school': 'Valparaiso', 'talent': 56.37, 'year': 2015},
 {'school': 'Western Illinois', 'talent': 51.28, 'year': 2015},
 {'school': 'McNeese', 'talent': 51.19, 'year': 2015},
 {'school': 'Duquesne', 'talent': 50.43, 'year': 2015},
 {'school': 'Charleston Southern', 'talent': 48.43, 'year': 2015},
 {'school': 'The Citadel', 'talent': 47.12, 'year': 2015},
 {'school': 'Eastern Illinois', 'talent': 46.56, 'year': 2015},
 {'school': 'Eastern Kentucky', 'talent': 46.5, 'year': 2015},
 {'school': 'Richmond', 'talent': 46.34, 'year': 2015},
 {'school': 'Eastern Washington', 'talent': 45.1, 'year': 2015},
 {'school': 'Texas Southern', 'talent': 43.1, 'year': 2015},
 {'school': 'Grambling', 'talent': 41.62, 'year': 2015},
 {'school': 'Coastal Carolina', 'talent': 41.5, 'year': 2015},
 {'school': 'Houston Baptist', 'talent': 39.71, 'year': 2015},
 {'school': 'Southern', 'talent': 37.48, 'year': 2015},
 {'school': 'Sacramento State', 'talent': 37.46, 'year': 2015},
 {'school': 'Rhode Island', 'talent': 37.17, 'year': 2015},
 {'school': 'Austin Peay', 'talent': 36.99, 'year': 2015},
 {'school': 'Fordham', 'talent': 36.98, 'year': 2015},
 {'school': 'Northern Colorado', 'talent': 36.95, 'year': 2015},
 {'school': 'Central Arkansas', 'talent': 35.29, 'year': 2015},
 {'school': 'Mercer', 'talent': 35.02, 'year': 2015},
 {'school': 'Norfolk State', 'talent': 32.59, 'year': 2015},
 {'school': 'Tennessee Tech', 'talent': 31.74, 'year': 2015},
 {'school': 'VMI', 'talent': 31.43, 'year': 2015},
 {'school': 'Campbell', 'talent': 31.21, 'year': 2015},
 {'school': 'Harvard', 'talent': 30.49, 'year': 2015},
 {'school': 'Southeast Missouri State', 'talent': 29.79, 'year': 2015},
 {'school': 'Cornell', 'talent': 29.11, 'year': 2015},
 {'school': 'Northwestern State', 'talent': 28.02, 'year': 2015},
 {'school': 'Presbyterian College', 'talent': 25.63, 'year': 2015},
 {'school': 'Delaware State', 'talent': 25.26, 'year': 2015},
 {'school': 'South Dakota State', 'talent': 25.25, 'year': 2015},
 {'school': 'Lamar', 'talent': 24.84, 'year': 2015},
 {'school': 'Nicholls', 'talent': 24.71, 'year': 2015},
 {'school': 'Alabama State', 'talent': 24.46, 'year': 2015},
 {'school': 'Kennesaw State', 'talent': 23.49, 'year': 2015},
 {'school': 'Idaho State', 'talent': 21.69, 'year': 2015},
 {'school': 'Columbia', 'talent': 21.24, 'year': 2015},
 {'school': 'New Hampshire', 'talent': 21.17, 'year': 2015},
 {'school': 'Prairie View', 'talent': 20.76, 'year': 2015},
 {'school': 'East Tennessee State', 'talent': 20.07, 'year': 2015},
 {'school': 'Weber State', 'talent': 19.8, 'year': 2015},
 {'school': 'Liberty', 'talent': 19.57, 'year': 2015},
 {'school': 'Wofford', 'talent': 19.48, 'year': 2015},
 {'school': 'Jacksonville', 'talent': 18.58, 'year': 2015},
 {'school': 'Brown', 'talent': 16.92, 'year': 2015},
 {'school': 'Western Carolina', 'talent': 15.77, 'year': 2015},
 {'school': 'Davidson', 'talent': 15.67, 'year': 2015},
 {'school': 'William & Mary', 'talent': 15.65, 'year': 2015},
 {'school': 'Florida A&M', 'talent': 15.6, 'year': 2015},
 {'school': 'Incarnate Word', 'talent': 15.59, 'year': 2015},
 {'school': 'North Carolina Central', 'talent': 14.26, 'year': 2015},
 {'school': 'Alabama A&M', 'talent': 13.33, 'year': 2015},
 {'school': 'Montana State', 'talent': 11.86, 'year': 2015},
 {'school': 'Butler', 'talent': 9.96, 'year': 2015},
 {'school': 'Gardner-Webb', 'talent': 8.58, 'year': 2015},
 {'school': 'Monmouth', 'talent': 7.93, 'year': 2015},
 {'school': 'Holy Cross', 'talent': 7.45, 'year': 2015},
 {'school': 'Drake', 'talent': 7.43, 'year': 2015},
 {'school': 'Maine', 'talent': 7.24, 'year': 2015},
 {'school': 'Lehigh', 'talent': 6.66, 'year': 2015},
 {'school': 'Stetson', 'talent': 6.66, 'year': 2015},
 {'school': 'Arkansas-Pine Bluff', 'talent': 6.66, 'year': 2015},
 {'school': 'Southern Utah', 'talent': 6.66, 'year': 2015},
 {'school': 'UC Davis', 'talent': 6.66, 'year': 2015},
 {'school': 'South Dakota', 'talent': 3.36, 'year': 2015},
 {'school': 'Robert Morris', 'talent': 3.06, 'year': 2015},
 {'school': 'Dartmouth', 'talent': 2.96, 'year': 2015},
 {'school': 'Marist', 'talent': 2.63, 'year': 2015},
 {'school': 'Howard', 'talent': 2.22, 'year': 2015},
 {'school': 'St Francis (PA)', 'talent': 1.74, 'year': 2015}]
type(test3)

list

In [74]:
test3df = pd.DataFrame(test3)
test3df

              school  talent  year
0            Alabama  981.90  2015
1                USC  926.71  2015
2         Ohio State  907.32  2015
3      Florida State  889.92  2015
4                LSU  889.37  2015
..               ...     ...   ...
227    Robert Morris    3.06  2015
228        Dartmouth    2.96  2015
229           Marist    2.63  2015
230           Howard    2.22  2015
231  St Francis (PA)    1.74  2015

[232 rows x 3 columns]

In [77]:
team_talent_2016_df = pd.DataFrame(team_talent_2016)
team_talent_2016_df

                                                     0
0    {'school': 'Alabama', 'talent': 982.66, 'year'...
1    {'school': 'USC', 'talent': 936.86, 'year': 2016}
2    {'school': 'LSU', 'talent': 917.72, 'year': 2016}
3    {'school': 'Florida State', 'talent': 906.64, ...
4    {'school': 'Ohio State', 'talent': 902.46, 'ye...
..                                                 ...
232  {'school': 'Central Connecticut', 'talent': 6....
233  {'school': 'San Diego', 'talent': 6.66, 'year'...
234  {'school': 'Bryant', 'talent': 6.24, 'year': 2...
235  {'school': 'North Carolina A&T', 'talent': 3.8...
236  {'school': 'St Francis (PA)', 'talent': 1.74, ...

[237 rows x 1 columns]

In [13]:
# get recruiting data for 2010-2021 seasons
import requests

headers = {
    'accept': 'application/json',
    'Authorization': 'Bearer 764WJr7XOG8TwqDCfJpNM3PUdPH9Iu5GQNq7pfXCzdDkm8DESnKeaaNMO3DlT9OW',
}

params = {
    'year': '2010',
    'year': '2011',
    'year': '2012',
    'year': '2013',
    'year': '2014',
    'year': '2015',
    'year': '2016',
    'year': '2017',
    'year': '2018',
    'year': '2019',
    'year': '2020',
    'year': '2021',
}

response = requests.get('https://api.collegefootballdata.com/recruiting/teams', params=params, headers=headers)

In [ ]:
sfd